### ISSUE TITLE
Footstep and Ripple Decals

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#155]

**Comment by Hoikas** [comment]
Without going into the ability to add particles (yes, apparently you can do particles here...) we need the following bindings:
- [ ] `plDynaDecalMgr`
- [ ] `plDynaRippleMgr` - for rippling water due to non-feet
- [ ] `plDynaRippleVSMgr` (use in wavesets)
- [ ] `plDynaPuddleMgr` - for rippling water due to feet
