### ISSUE TITLE
Don't average/pack lightmap UVs.

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#265]
Currently, Korman averages and packs UV islands in an artist specified UV texture for lightmaps. This is undesirable in light of #261, which will enable the lightmap texture to persist. Additionally, @Jrius alludes to other [issues](https://github.com/H-uru/korman/pull/261#issuecomment-890504917) with this forced process, however there was no elaboration about what those issues were. However, it is a requirement in the case of objects with Blender modifiers - without this process, lighting will be duplicated onto newly generated sections of mesh.

There are a few ways we can proceed:
- Only do the average/pack process if we detect modifiers on the object.
   - This may result in surprising behavior?
- Add a checkbox on the lightmap modifier for enabling the forced average/pack process.
   - What should the default value be?
   - This seems overly tedious.
- Deprecate artist supplied UV maps on objects with modifiers. Conditionally allow it with the average/pack process if an certain export policy is set, otherwise, error.
    - Export policies are currently in discussion on IRC. They would look and work somewhat like [CMake Policies](https://cmake.org/cmake/help/latest/manual/cmake-policies.7.html).

**Comment by Jrius** [comment]
Lightmap UVs are a complex topic as soon as you throw in modifiers (especially the array one) and persistent lightmaps, so this will probably need several people's opinion on top of extensive testing to make sure there are no edge cases.

To expand on my previous problems with Korman's unwrapping.
- As I mentioned, it's common for artists to have overlapping UVs within the same UV island for their diffuse texture. Should this UVmap be used for lightmapping, this will cause pixels to be shared between two faces, which will screw up the resulting lightmap. Rescaling+packing will not fix it. Thus, if the artist does not supply the lightmap UVmap, Korman should create one from scratch instead of reusing the base UVmap intended for the diffuse texture.
- Currently, Korman always rescales+packs the UV islands. If the artist supplies his own UVmap, this should be avoided. Blender's UV island packing operates on island bounding boxes (or hulls ? don't remember) and ignores concave island shapes. This can potentially result in a huge waste of lightmap pixel space (not so much for simple meshes, but it's common for more complex ones). Artists are better at arranging concave shapes in a way to maximize UV coverage. Also, artists may want to scale each UV island independently to allocate more pixels to a specific island (mostly to provide more pixels to areas with high-frequency shadows), so averaging their scale should also be avoided if possible.
- Korman doesn't specify an island margin while packing islands. Lightmappers need island margins for a few reasons - mostly because once the lightmap is projected on-screen, pixel interpolation may leak pixels _beyond_ the UV island. Thus, UV islands should be kept further apart, which also lets Blender's lightmapper extend the baking a few pixels beyond the UV island to avoid any pixel leaking. (See the Bake Margin field in the bake panel.)

Because of this, my recommendations for UV unwrapping for lightmapping are:
- **No modifier, but artist-supplied UVmap**: use the UV map, don't modify it at all.
- **No modifier, no artist-supplied UVmap**: use `bpy.ops.uv.smart_project(island_margin=0.05)`. This avoids UV overlaps, keeps pixel density consistent across the mesh (unlike regular unwrap), avoids unnecessary seams (unlike "lightmap pack"), and keeps a reasonable island margin for the lightmapper. The island margin of 0.05 might need tweaking (not sure what it's based off, ideally it should be computed according to lightmap size and bake margin), but in my experience 0.05 gave correct results on most meshes.
- **Modifiers, artist-supplied UVmap**: use island packing (no need for averaging island scale IMHO), but warn in the lightmap modifier about the requirement to pack islands. Hopefully that won't result in strange behavior... (Island packing can also produce different results if applied multiple times, which could cause issues with persistent lightmaps.)
- **Modifiers, no artist-supplied UVmap**: use smart_project like earlier.

I don't have too much experience lightmapping objects with modifiers so I may be forgetting some things. Thoughts are welcome :)

As for policies, if I understand correctly they would work like some global setting stored in the Blender file ? Then I'm not really fond of the idea, to be honest. In my humble opinion, the export process should be the same for all users and Blender files to avoid confusion, and any override should be per-object. Global settings should only be used for UI and workflow improvements, not change in export behavior.
But that's just my opinion, of course. :shrug:

**Comment by Hoikas** [comment]
Thanks for the input @Jrius - your suggestions are largely in line with my first point and what @dpogue has suggested. So, I think we will go with that. Do you think that in the no **no artist supplied UVmap** case, we should consider packing the islands as well, or will the `island_margin=0.05` handle that force us? We don't currently pass an `island_margin` into the smart project, and I have noticed that has some bad results in same cases.

**Comment by Jrius** [comment]
My pleasure ;)

> Do you think that in the no no artist supplied UVmap case, we should consider packing the islands as well, or will the island_margin=0.05 handle that force us?

Packing fits islands within the [0..1] range with a margin between each island, which smart project already does as long as island_margin is specified. So no need to do this again, unless new geometry was created since the smart project, of course.

(Oh, and just in case, "smart project" and "pack islands" use the margin differently for some reason. `pack_islands` with an `island_margin` of 0.01 is roughly equivalent to `smart_project` with a `margin` of 0.05. Don't ask why... :roll_eyes: )

**Comment by Hoikas** [comment]
> (Oh, and just in case, "smart project" and "pack islands" use the margin differently for some reason. pack_islands with an island_margin of 0.01 is roughly equivalent to smart_project with a margin of 0.05. Don't ask why... 🙄 )

I don't need to ask... The reason is: "because Blender" 😜
