### ISSUE TITLE
Animated child object improvement observation

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#284]
While working on Descent, I've noticed that, when there's child objects with animation that are  parented, the "affine parts" of the ATC animation that are exported by Korman are incorrect, specifically the T value, which currently just uses the child object's location in Blender. Here's what I've observed:

* For the top parent object (ie not parented to anything else), the affine parts' **hsVector T value** is the location as it appears in Blender like Korman does now.
* For subsequent child objects that are also animated, the affine parts' **hsVector T value** is the child object's origin's offset distance from the parent's origin.

Sadly, I don't know exactly where to go in the coding to fix all this or to tell Korman to do this only for child objects, so I'm posting the issue here.

**Comment by Hoikas** [comment]
After some investigation yesterday, I determined that the CI of some child objects are incorrect, specifically the Parent2Local and Local2Parent components. An example of an affected object hierarchy is if the butterflies from Myst 5's Descent are imported via ZLZ and exported through Korman. For example, ButterflyAWingo01. The butterflies appear correctly in Blender, however, on re-export they appear somewhere way off in the distance, and the CIs are incorrect as mentioned. The incorrect objects seem to have quaternion animations, but I suspect that is only a casual relationship.

Any ideas @Jrius? You're way better at this math than I am 😄

**Comment by Jrius** [comment]
There are no coincidences when quaternion animations are involved ! XD
More seriously though. I imported Descent (both EoA and Drizzle'd) and reexported, the butterflies seem correctly animated on my end (aside from upside-down wings maybe, but that's a known defect). I can see them fluttering around in the volcano, they look correctly positioned. I'm using the latest masters from both Korman and ZLZ.
If you can upload the defective files somewhere (both blend and prp) I'll have a look.

**Comment by Hoikas** [comment]
I've emailed both files to the address you have on file on the forum.

**Comment by Jrius** [comment]
Ah, I see. Somehow the transform of objects in the hierarchy got completely fck'ed up, the animation is supposed to look a bit different even in Blender. Then there is some weirdness happening with `object.location` returning world position instead of local pos like it should.
I'll investigate, this sounds like both Korman and the files need to be fixed...

**Comment by Jrius** [comment]
Okay, so after some looong tests...
Blender maintains multiple matrices to make things needlessly complex when dealing with parenting, which makes life hard for us. I'm not kidding, better grab a chair and some popcorn...

Let's see what matrices we have in Blender:
- `matrix_world`: the world-space transform of the object after all parenting is applied. Equivalent to L2W in Plasma. Common in any tool/game engine.
- `matrix_local`: the local-space transform of the object, which is applied after the parent's own transform. Equivalent to L2P. Common in any tool/game engine.
- `matrix_basis` and `matrix_parent_inverse`: NOT common in other tools/engines. Look like some kind of elaborate (read: annoying) way of storing the object's location before it was parented or something. Basically, two children objects can have the SAME `matrix_local` and `matrix_world` (=local/world transforms), but COMPLETELY different `matrix_basis` and `matrix_parent_inverse`. Those matrices _entirely_ depend on the order in which the artist parented/moved both the parent and the child object. In an ideal world, these matrices should be of _no use at all_ to us programmers.

Thus, both Korman and ZLZ should always use `matrix_local` and `matrix_world` instead, depending on whether we want local or world transform. Simple, right ?
But HEEEY... You didn't think it would be THAT simple, would you ? :zany_face: It gets much, much better.

Guess what. `object.location` is the transform part of the `matrix_basis` (probably the same for rotation/scale ? Haven't tested). Which means `object.location` is some random vector that represents NEITHER local position NOR world position - it could be anything !
So what's the big deal, let's just not use it, right ?
Ah, but unfortunately Blender will force us to. Remember what we're keyframing when animating an object ? That's right. We're keying `object.location`.

Yes.

If we have objects A, B, C, D... with the SAME  `matrix_local`/`matrix_world`, both parented to the SAME parent object, and sharing the SAME action/animation... Object A might animate in local space, while B might animate in world space, while C and D could animate in any space they want !
This might be smart if the artists were actually aware of how to exploit parenting to create animations that are either local or global. But, since I'm pretty sure 99% of Blender users don't, then this feature is massively stupid and annoying.

When writing ZLZ, I wasn't paying attention and mixed usage of all four matrices. Fortunately for me, it appears this ended up in ZLZ importing animations in local space, which is exactly what we want. At least, until something else breaks. For some reason, Doobes' file got screwed up anyway, but I don't know if it's because of an older version of ZLZ or just random manipulation error.
But anyway, depending on how artists parented their objects before animating them, Korman will likely have to deal with non-local animations.

To be continued. Tomorrow or the day after that I'll try to fix Korman, ZLZ and Doobes' file, and see if I was right about all I've written so far. Hopefully there won't be more nasty surprises.

In the meantime I'm gonna eat something, I'm starving :sweat_smile: 

(And if you still have some popcorn left, go have a look at how Blender animations interpolate quaternions for more software gore...)

**Comment by Hoikas** [comment]
That sounds like some great investigative work, @Jrius. I had no idea that Blender would allow the `object.location` to be anything other than parent space. This is worse than #287. Thanks for looking into this!

**Comment by DoobesURU** [comment]
> 
> 
> That sounds like some great investigative work, @Jrius. I had no idea that Blender would allow the `object.location` to be anything other than parent space. This is worse than #287. Thanks for looking into this!

Just seconding what @Hoikas said. Thanks for looking into this, @Jrius !

**Comment by Jrius** [comment]
@DoobesUru, could you please do the following: download [this file](https://www.dropbox.com/s/gglze1c25dmh477/restore_matrices.py?dl=1), paste its content into a text file in your Descent Blender file, and run (ctrl-p) it ? It should reset the position for ALL objects in Descent to what ZLZ currently imports. If you look closely at the butterflies in the volcano, their anim should be slightly more complex and closer to the original.
Remember to backup your file. If you moved some objects around since importing, their location will be reset...
